export const START_FETCH_ARTICLES = 'ARTICLES/START_FETCH_ARTICLES';
export const END_FETCH_ARTICLES = 'ARTICLES/END_FETCH_ARTICLES';
export const START_CREATE_ARTICLE = 'ARTICLES/START_CREATE_ARTICLE';
export const END_CREATE_ARTICLE = 'ARTICLES/END_CREATE_ARTICLE';